def on_a_pressed():
    # If this hitting bottom not added sprite can fly just by hitting button A and always wins :)
    # 
    if boyJumper.is_hitting_tile(CollisionDirection.BOTTOM):
        boyJumper.vy = -200
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

boyJumper: Sprite = None
tiles.set_current_tilemap(tilemap("""
    level1
"""))
boyJumper = sprites.create(img("""
        ........................
            ....ffffff..............
            ..ffeeeef2f.............
            .ffeeeef222f............
            .feeeffeeeef...cc.......
            .ffffee2222ef.cdc.......
            .fe222ffffe2fcddc.......
            fffffffeeeffcddc........
            ffe44ebf44ecddc.........
            fee4d41fddecdc..........
            .feee4dddedccc..........
            ..ffee44e4dde...........
            ...f222244ee............
            ...f2222e2f.............
            ...f444455f.............
            ....ffffff..............
            .....fff................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
    """),
    SpriteKind.player)
tiles.place_on_tile(boyJumper, tiles.get_tile_location(1, 5))
boyJumper.ay = 500